export const BACKGROUND_COLOR = '#FFFFFF';
export const WARNING_BACKGROUND_COLOR = '#fc9fa3';
export const WARNING_BACKGROUND_COLOR_2 = '#f2b3b6';
export const WARNING_BACKGROUND_ACCENT_COLOR = '#e38f93';
export const WARNING_PRIMARY_COLOR = '#FC4549';
export const COMPLETED_BACKGROUND_COLOR = '#5cd160';
export const COMPLETED_BACKGROUND_COLOR_2 = '#7bd17e';
export const COMPLETED_BACKGROUND_ACCENT_COLOR = '#4bad4e';
export const NEUTRAL_BACKGROUND_COLOR = '#E1EDF9';
export const BOTTOM_TAB_BACKGROUND_COLOR = '#FFFFFF';
export const BOTTOM_TAB_SELECT_COLOR = '#1B6BCA';
export const PRIMARY_TEXT_COLOR = '#000000';

export const TEXT_INPUT_BACKGROUND_COLOR = '#FFFFFF';
export const TEXT_DISABLED_BACKGROUND_COLOR = '#E5E5E5';
export const TEXT_INPUT_HINT_COLOR = '#A9A9A990';
export const TEXT_DISABLED_COLOR = '#5E5E5E';
export const TEXT_INPUT_SHADOW_COLOR = '#000000';

export const BUTTON_GREEN_BACKGROUND_COLOR = '#99C9B2';
export const BUTTON_BLUE_BACKGROUND_COLOR = '#99C0C9';
export const BUTTON_BORDER_COLOR = '#FFFFFF';
export const BUTTON_TEXT_COLOR = '#FFFFFF';

export const TEXT_SECONDARY_LABEL_COLOR = '#00000060';
export const TEXT_SECONDARY_COLOR = '#00000095';